/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 sap.gltf --transform
Author: emad-tvk (https://sketchfab.com/emad-tvk)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/niko-bellic-gta-iv-35779f753eb04dfe9eb5886dce27ec43
Title: Niko Bellic GTA IV
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("../../public/img/sap-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.Object002_mtl}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.Object002_mtl}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/sap-transformed.glb");
